spring:
  datasource:
    url: jdbc:mysql://localhost/logic_word?useUnicode=true&characterEncoding=UTF-8
    username: logicword
    password: logicword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update